server.port=${PORT:8083}
spring.data.mongodb.uri=mongodb+srv://icps_user:vg9vMPatq2Ig4IZQ@authdb.yzw9hzs.mongodb.net/paymentdb?appName=authdb
spring.data.mongodb.database=paymentdb

jwt.secret=${JWT_SECRET}
jwt.expiry=${JWT_EXPIRY:86400000}
